pipeline {
    agent any
   stages {
               stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/master']], extensions: [],
userRemoteConfigs: [[url: 'https://github.com/Samarinnayak/demo.git']])
                echo 'successful checkout'
    } }
    stage('Build and Package') {
        steps {
            withMaven(maven: 'maven') {
                sh 'mvn clean install'
              echo 'successful Build and Package'
            }
} }
    stage('Build Docker Image') {
        steps {
            script {
                def imageTag = "samarinnayak/demo:latest"
                docker.build(imageTag, '.')
                echo 'successful Build Docker Image'
} }
}
    stage('Push to Docker Hub') {
        steps {
            script {
                withDockerRegistry(credentialsId: 'docker_hub_cred', url: 'https://index.docker.io/v1/') {
                    def imageTag = "samarinnayak/demo:latest"
                    docker.image(imageTag).push()
                    echo 'successful Push to Docker Hub'
                }
} }
}
     stage('Deploy to Kubernetes') {
             stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'docker_hub_cred', serverUrl: 'https://my-kubernetes-cluster.com']) {
                    sh "kubectl apply -f kubernetes-config.yaml"
                }
            } }
} }}
